using GoogleTranslateNET.Misc;

namespace GoogleTranslateNET
{
    public enum Language
    {
        Unknown,
        Automatic,
        [StringValue("af")]
        Afrikaans,
        [StringValue("sq")]
        Albanian,
        [StringValue("ar")]
        Arabic,
        [StringValue("be")]
        Belarusian,
        [StringValue("bg")]
        Bulgarian,
        [StringValue("ca")]
        Catalan,
        [StringValue("zh")]
        ChineseSimplified,
        [StringValue("zh-TW")]
        ChineseTraditional,
        [StringValue("hr")]
        Croatian,
        [StringValue("cs")]
        Czech,
        [StringValue("da")]
        Danish,
        [StringValue("nl")]
        Dutch,
        [StringValue("en")]
        English,
        [StringValue("eo")]
        Esperanto,
        [StringValue("et")]
        Estonian,
        [StringValue("tl")]
        Filipino,
        [StringValue("fi")]
        Finnish,
        [StringValue("fr")]
        French,
        [StringValue("gl")]
        Galician,
        [StringValue("de")]
        German,
        [StringValue("el")]
        Greek,
        [StringValue("ht")]
        HaitianCreole,
        [StringValue("iw")]
        Hebrew,
        [StringValue("hi")]
        Hindi,
        [StringValue("hu")]
        Hungarian,
        [StringValue("is")]
        Icelandic,
        [StringValue("id")]
        Indonesian,
        [StringValue("ga")]
        Irish,
        [StringValue("it")]
        Italian,
        [StringValue("ja")]
        Japanese,
        [StringValue("ko")]
        Korean,
        [StringValue("lv")]
        Latvian,
        [StringValue("lt")]
        Lithuanian,
        [StringValue("mk")]
        Macedonian,
        [StringValue("ms")]
        Malay,
        [StringValue("mt")]
        Maltese,
        [StringValue("no")]
        Norwegian,
        [StringValue("fa")]
        Persian,
        [StringValue("pl")]
        Polish,
        [StringValue("pt")]
        Portuguese,
        [StringValue("ro")]
        Romanian,
        [StringValue("ru")]
        Russian,
        [StringValue("sr")]
        Serbian,
        [StringValue("sk")]
        Slovak,
        [StringValue("sl")]
        Slovenian,
        [StringValue("es")]
        Spanish,
        [StringValue("sw")]
        Swahili,
        [StringValue("sv")]
        Swedish,
        [StringValue("th")]
        Thai,
        [StringValue("tr")]
        Turkish,
        [StringValue("uk")]
        Ukrainian,
        [StringValue("vi")]
        Vietnamese,
        [StringValue("cy")]
        Welsh,
        [StringValue("yi")]
        Yiddish
    }
}